### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by nuexq** [pdonadeo/rofi-web-search#10]
i have no experience on rofi so how to install pls

**Comment by pdonadeo** [comment]
What Linux distribution are you using?

**Comment by nuexq** [comment]
arch linux hyprland WM

**Comment by pdonadeo** [comment]
Excellent! I think you should read [this article](https://wiki.archlinux.org/title/Rofi), which is very detailed about how to install and use rofi.

**Comment by nuexq** [comment]
I already install rofi I want to know how to install the plugin rofi web search

**Comment by pdonadeo** [comment]
Ok, no need to really install anything: just clone the repo:
```bash
gh repo clone pdonadeo/rofi-web-search
```

and copy the script `rofi-web-search.py` in a directory in your `$PATH`.

Then configure Hyprland to launch the script. I'm not an Hyprland user so I cannot help in this.

**Comment by nuexq** [comment]
thanks man for help
