### ISSUE TITLE
shebang appears incorrect

### ISSUE THREAD

**Issue by gsornsen** [pdonadeo/rofi-web-search#5]
I'd like to propose changing the shebang at the top of the file from:
```python
#!/bin/env python3
```
to:
```python
#!/usr/bin/env python3
```

I don't have /bin/env on my machine.

```bash
(base) gsornsen@pop-os:~/git/rofi-web-search$ ls /bin/env
ls: cannot access '/bin/env': No such file or directory
(base) gsornsen@pop-os:~/git/rofi-web-search$ ls /usr/bin/env
/usr/bin/env
```

[This stackoverflow post](https://stackoverflow.com/questions/6908143/should-i-put-shebang-in-python-scripts-and-what-form-should-it-take) also recommends using /usr/bin/env python3 as well.

Let me know if you'd like to change it and I'll initiate the PR.

**Comment by pdonadeo** [comment]
You are totally right. Start a simple PR, I'll merge it instantly.

**Comment by gsornsen** [comment]
@pdonadeo 

Apologies for the delay. Work's been a bit crazy and I'm flying across the country for a wedding.
