### ISSUE TITLE
Enhancement/Suggestion: External Configuration File

### ISSUE THREAD

**Issue by gsornsen** [pdonadeo/rofi-web-search#7]
@pdonadeo 

I'd like to work on bringing the:
* `SEARCH_ENGINE`
* `BROWSER`
* `TERMINAL`
* `CONFIG`

Objects out to a `config.json` or (`config.yaml` file if you're okay with adding `ruamel.yaml` or `pyyaml` as a dependency). The new config file would live in user space under `~/.config/rofi-web-search/config.json` or `~/.config/rofi-web-search/config.yaml`

This will coincide with  #8 (Static Binary/Rudimentary Build System)

I'd be happy to take on this work as I'll have a couple of long, boring flights the next three days.

**Comment by pdonadeo** [comment]
Done, but a couple of notes:
* `CONFIG` is pointless because different search engines require different code, not only different configuration.
* JSON is OK, YAML nope, because I want to keep the script simple, with absolutely no external dependency.
