### ISSUE TITLE
Enhancement/Suggestion: Static Binary/Rudimentary Build System

### ISSUE THREAD

**Issue by gsornsen** [pdonadeo/rofi-web-search#8]
@pdonadeo 

This suggestion is built on top of #7 (External Configuration).

I'd like to write a Makefile that uses `pyinstaller` to create a static binary and "install" the binary as `/usr/bin/rofi-web-search` and the external config as `~/.config/rofi-web-search/config.json` or as `~/.config/rofi-web-search/config.yaml`

Users would be able to clone the repository and run `make install` to compile and install the binary/config on their system.

I would also add a `requirements.txt` file and have the make file automagically fetch any dependencies requires to build the binary.

I'd be happy to take on this work as I'll have a couple of long, boring flights the next three days.

**Comment by pdonadeo** [comment]
Nope, sorry :)

As stated in #7 I want to keep this script simple. An external configuration is useful because one could keep different settings on different machines/users. But a static binary is too much. Why then? Python 3 is installed by default... everywhere in the Linux world.
