### ISSUE TITLE
launch brave

### ISSUE THREAD

**Issue by thanasisn** [pdonadeo/rofi-web-search#9]
It works as expected but only when I have brave running.
Doesn't seem to execute brave when it is not running.
I try with "brave-browser --new-window" as my browser in the py script and does not work.
Any suggestions??

**Comment by pdonadeo** [comment]
Sorry I cannot reproduce this bug. With Brave Browser 86.1.16.76 it works like a charm.

What operating system are you using?

**Comment by thanasisn** [comment]
It is fine now!
I thing it was a reconfigure somewhere.
Thanks a lot!!
